/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Detect the document format from raw bytes.
 *
 * # Errors
 *
 * Returns an error if the format cannot be determined from the content.
 */
export declare function detectFormat(content: Buffer): string
/**
 * Extract the intermediate representation as JSON.
 *
 * # Errors
 *
 * Returns an error if format detection or extraction fails.
 */
export declare function extractIrJson(content: Buffer, format?: string | undefined | null): string
/**
 * Render document bytes as Markdown.
 *
 * # Errors
 *
 * Returns an error if format detection, extraction, or rendering fails.
 */
export declare function markdownFromBytes(content: Buffer, format?: string | undefined | null, includeDocumentProperties?: boolean | undefined | null, useFirstRowAsHeader?: boolean | undefined | null, includeHeadersFooters?: boolean | undefined | null, markdownStyle?: string | undefined | null): string
/**
 * Render multiple documents as Markdown with Rust-side parallel workers.
 *
 * # Errors
 *
 * Returns an error if any item fails format detection, extraction, or rendering.
 */
export declare function markdownFromBytesBatch(contents: Array<Buffer>, format?: string | undefined | null, workers?: number | undefined | null, includeDocumentProperties?: boolean | undefined | null, useFirstRowAsHeader?: boolean | undefined | null, includeHeadersFooters?: boolean | undefined | null, markdownStyle?: string | undefined | null): Array<string>
/**
 * Extract sheet names from an XLSX workbook.
 *
 * # Errors
 *
 * Returns an error if the content is not a valid XLSX workbook.
 */
export declare function extractSheetNames(content: Buffer): Array<string>
/**
 * Extract XLSX table data as a JSON string.
 *
 * # Errors
 *
 * Returns an error if XLSX extraction or JSON serialization fails.
 */
export declare function extractTablesIrJson(content: Buffer, styleAwareValues?: boolean | undefined | null, streamingRows?: boolean | undefined | null, includeDocumentProperties?: boolean | undefined | null): string
/**
 * Extract CSV table data as a JSON string.
 *
 * # Errors
 *
 * Returns an error if the delimiter is invalid or CSV extraction fails.
 */
export declare function extractCsvTablesIrJson(content: Buffer, delimiter?: string | undefined | null, includeDocumentProperties?: boolean | undefined | null): string
/**
 * Inspect a PDF and return diagnostics as JSON.
 *
 * # Errors
 *
 * Returns an error if the content is not a valid PDF or inspection fails.
 */
export declare function inspectPdfJson(content: Buffer): string
/**
 * Inspect PDF font information and return as JSON.
 *
 * # Errors
 *
 * Returns an error if the content is not a valid PDF or font inspection fails.
 */
export declare function inspectPdfFontsJson(content: Buffer): string
/**
 * Convert document bytes to Docling JSON format.
 *
 * # Errors
 *
 * Returns an error if format detection, extraction, or Docling conversion fails.
 */
export declare function doclingFromBytes(content: Buffer, format?: string | undefined | null): string
