from __future__ import annotations

from collections.abc import Sequence

def detect_format(content: bytes) -> str: ...
def inspect_pdf_json(content: bytes) -> str: ...
def inspect_pdf_fonts_json(content: bytes) -> str: ...
def extract_ir_json(content: bytes, format: str | None = None) -> str: ...
def docling_from_bytes(content: bytes, format: str | None = None) -> str: ...
def create_document_from_markdown(markdown: str, format: str) -> bytes: ...
def apply_ooxml_patch_json(content: bytes, patch_json: str) -> bytes: ...
def _patch_docx_json(content: bytes, patch_json: str) -> bytes: ...
def _patch_pptx_json(content: bytes, patch_json: str) -> bytes: ...
def _patch_xlsx_json(content: bytes, patch_json: str) -> bytes: ...
def _patch_docx_json_with_report(content: bytes, patch_json: str) -> str: ...
def _patch_pptx_json_with_report(content: bytes, patch_json: str) -> str: ...
def _patch_xlsx_json_with_report(content: bytes, patch_json: str) -> str: ...
def _patch_docx_batch_json(
    contents: Sequence[bytes],
    patch_json: str,
    workers: int | None = None,
) -> list[bytes]: ...
def _patch_pptx_batch_json(
    contents: Sequence[bytes],
    patch_json: str,
    workers: int | None = None,
) -> list[bytes]: ...
def _patch_xlsx_batch_json(
    contents: Sequence[bytes],
    patch_json: str,
    workers: int | None = None,
) -> list[bytes]: ...
def _patch_docx_batch_json_with_report(
    contents: Sequence[bytes],
    patch_json: str,
    workers: int | None = None,
) -> str: ...
def _patch_pptx_batch_json_with_report(
    contents: Sequence[bytes],
    patch_json: str,
    workers: int | None = None,
) -> str: ...
def _patch_xlsx_batch_json_with_report(
    contents: Sequence[bytes],
    patch_json: str,
    workers: int | None = None,
) -> str: ...
def markdown_from_bytes(
    content: bytes,
    format: str | None = None,
    **render_settings: object,
) -> str: ...
def markdown_from_bytes_batch(
    contents: Sequence[bytes],
    format: str | None = None,
    workers: int | None = None,
    **render_settings: object,
) -> list[str]: ...
def extract_sheet_names(content: bytes) -> list[str]: ...
def extract_tables_ir_json(
    content: bytes,
    style_aware_values: bool = False,
    streaming_rows: bool = False,
    include_document_properties: bool = False,
) -> str: ...
def extract_csv_tables_ir_json(
    content: bytes,
    delimiter: str = ",",
    include_document_properties: bool = False,
) -> str: ...
